# Project identification
sonar.projectKey=newrep3
sonar.projectName=newrep3
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Language and version
sonar.language=py
sonar.python.version=3

# Encoding
sonar.sourceEncoding=UTF-8

