sonar.projectKey=newrep3_python
sonar.projectName=NewRep3 Python Project
sonar.projectVersion=1.0

# Only scan py1.py
sonar.sources=py1.py

# Point to your SonarQube server
sonar.host.url=http://localhost:9000

sonar.login=admin
sonar.password=Nte#25

sonar.exclusions=__pycache__/**,tests/**

